# Generated by Django 4.2.6 on 2023-10-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('descriptions', models.TextField()),
                ('price', models.FloatField()),
                ('discount', models.IntegerField()),
                ('in_stock', models.IntegerField()),
                ('quantite', models.IntegerField()),
                ('categories', models.CharField(choices=[('informatique et Multimedia', 'IM'), ('Vehicules', 'V'), ('Immobilier', 'I'), ('Maison et bureau', 'MB'), ('Beaute et bienetre', 'BB'), ('Loisirs', 'L')], max_length=26)),
            ],
        ),
    ]
