# Generated by Django 4.2.6 on 2023-10-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_managements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
