# Generated by Django 4.2.6 on 2023-10-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_managements', '0002_alter_products_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='categories',
            field=models.CharField(choices=[('IM', 'informatique et Multimedia'), ('V', 'Vehicules'), ('I', 'Immobilier'), ('MB', 'Maison et bureau'), ('BB', 'Beaute et bienetre'), ('L', 'Loisirs')], max_length=26),
        ),
    ]
