# Generated by Django 4.2.6 on 2023-10-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id_store', models.IntegerField(primary_key=True, serialize=False)),
                ('name_store', models.CharField(max_length=50)),
                ('adresse_store', models.CharField(max_length=50)),
                ('incomes', models.FloatField()),
                ('name_of_the_owner', models.CharField(max_length=50)),
                ('age_of_the_owner', models.IntegerField()),
            ],
        ),
    ]
