# Generated by Django 4.2.6 on 2023-10-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores_managements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='adresse_store',
            new_name='store_adresse',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='incomes',
            new_name='store_incomes',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='name_store',
            new_name='store_name',
        ),
        migrations.RemoveField(
            model_name='store',
            name='age_of_the_owner',
        ),
        migrations.RemoveField(
            model_name='store',
            name='name_of_the_owner',
        ),
        migrations.AddField(
            model_name='store',
            name='store_description',
            field=models.TextField(default='Write your description'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='store',
            name='store_link_facebook',
            field=models.CharField(default='Link facebook', max_length=500),
        ),
        migrations.AddField(
            model_name='store',
            name='store_link_instagram',
            field=models.CharField(default='Link facebook', max_length=500),
        ),
        migrations.AddField(
            model_name='store',
            name='store_link_linkedin',
            field=models.CharField(default='Link facebook', max_length=500),
        ),
        migrations.AddField(
            model_name='store',
            name='store_numero1',
            field=models.TextField(default='Write your number'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_numero2',
            field=models.TextField(default='Write your number'),
        ),
    ]
