# Generated by Django 4.2.6 on 2023-10-26 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores_managements', '0002_rename_adresse_store_store_store_adresse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='id_store',
            new_name='store_id',
        ),
    ]
