# Generated by Django 4.2.6 on 2023-10-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id_facture', models.IntegerField(primary_key=True, serialize=False)),
                ('montant_facture', models.FloatField()),
                ('id_commande', models.IntegerField()),
                ('id_client', models.IntegerField()),
            ],
        ),
    ]
