# Generated by Django 4.2.6 on 2023-10-26 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factures_managements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='id_facture',
            new_name='facture_id',
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='id_client',
            new_name='facture_id_client',
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='id_commande',
            new_name='facture_id_commande',
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='montant_facture',
            new_name='facture_montant',
        ),
    ]
