# Generated by Django 4.2.6 on 2023-10-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderId', models.IntegerField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=50)),
                ('Ordered', models.DateTimeField()),
                ('Shipped', models.DateTimeField()),
                ('ShippingAdress', models.CharField(max_length=50)),
                ('Order_status', models.BooleanField()),
                ('Total', models.FloatField()),
            ],
        ),
    ]
